name: Android CI

on:
  push:
    branches: [ custom, sideload ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Execute launcher dispatch event
      if: contains(github.ref, 'sideload')
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
      run: |
        gh api repos/SamSprung/SamSprung-TooUI/dispatches --raw-field event_type=SamSprung
    - name: Execute widget dispatch event
      if: contains(github.ref, 'custom')
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
      run: |
        gh api repos/SamSprung/SamSprung-Widget/dispatches --raw-field event_type=SamSprung
