name: Android CI

on:
  push:
    branches: [ sideload ]
  pull_request:
    branches: [ sideload ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Execute repository dispatch event
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
      run: |
        gh api repos/SamSprung/SamSprung-Launcher/dispatches --raw-field event_type=SamSprung
